version: '3'
services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    environment:
      DOMAINS: 'www.takopanman.work -> http://django:8000'
      STAGE: 'production'
  
  django:
    build:
      context: ./django
    image: django:1.0
    environment:
      - DJANGO_SETTINGS_MODULE=upload.settings
      - DATABASE_DB=django
      - DATABASE_USER=djangoadmin
      - DATABASE_PASSWORD=adminPassword
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
    restart: always
    ports:
      - 8000:8000 #OSの80をコンテナの8000と紐づける
    volumes:
      - data:/data
      - media:/django/media
    depends_on:
      - db

  db:
    image: postgres:11.4-alpine
    container_name: db
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=django
      - POSTGRES_USER=djangoadmin
      - POSTGRES_PASSWORD=adminPassword
      - POSTGRES_INITDB_ARGS="--encoding=UTF-8"
    hostname: db
    restart: always

  schedule:
    image: schedule:1.0
    restart: always
    build:
      context: ./schedule

volumes:
  postgres_data:
  data:
  media: