version: '3'
services:
  django:
    build:
      context: ./django
    image: django:1.0
    environment:
      - DJANGO_SETTINGS_MODULE=upload.settings
      - DATABASE_DB=django
      - DATABASE_USER=djangoadmin
      - DATABASE_PASSWORD=adminPassword
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
    restart: always
    ports:
      - 80:8000
    volumes:
      - data:/data
      - media:/media
    depends_on:
      - db

  db:
    image: postgres:11.4-alpine
    container_name: db
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=django
      - POSTGRES_USER=djangoadmin
      - POSTGRES_PASSWORD=adminPassword
      - POSTGRES_INITDB_ARGS="--encoding=UTF-8"
    hostname: db
    restart: always


volumes:
  postgres_data:
  data:
  media: