# Generated by Django 3.0.5 on 2020-04-02 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_filename_pwd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filename',
            name='pwd',
        ),
    ]
