# Generated by Django 3.0.5 on 2020-04-03 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_remove_filename_pwd'),
    ]

    operations = [
        migrations.AddField(
            model_name='filename',
            name='pwd',
            field=models.CharField(default=2, max_length=70),
            preserve_default=False,
        ),
    ]
